# Generated by Django 4.2.3 on 2023-07-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('chip_id', models.TextField()),
                ('way', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='chip_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_id', models.TextField()),
                ('chip_name', models.TextField()),
                ('chip_ico', models.TextField()),
                ('can_drop', models.TextField()),
            ],
        ),
    ]
