# Generated by Django 4.2.3 on 2023-07-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.TextField()),
                ('case_drop', models.TextField()),
            ],
        ),
    ]
